### ISSUE TITLE
[BUG] Buttons aren't responding

### ISSUE THREAD

**Issue by rexelbartolome** [padvincenzo/silence-speedup#10]
UI doesn't seem to respond to clicks and basically no button is working on ver 1.2.4

1. Extract 1.2.4 win32-x64 standalone version
2. Open Silence-Speedup
3. Interact with buttons (see attached)

https://user-images.githubusercontent.com/88552647/150782142-a19165fa-09d6-49f3-a24c-1a633a6c2638.mp4

**Comment by padvincenzo** [comment]
Thank you @rexelbartolome for writing me so quick. It is a problem with my export script, I've updated it so this won't happen again.
I'm uploading a new version, and I'll follow your advice to forget about a normal/standalone versions.
