### ISSUE TITLE
[BUG] UI elements overlapping due to Windows forcing "sane" resizing logic

### ISSUE THREAD

**Issue by Joey-Haney** [padvincenzo/silence-speedup#5]
**Describe the bug**

For my monitor resolution of 1600 x 900, the window opened with the buttons for starting and to switch to progress mode covered by the lower portion of the window which reports the time, speed, and current status. This prevented me from using the buttons. 
I was able to get around this by making my taskbar location go to the left or right side. This freed up about 40 pixels or so of space which allowed the buttons to be only half covered but clickable. 

**To Reproduce**
1. Run the Executable
2. Try to click on the buttons
3. try to resize the window
4. Windows enforces "sane" resizing rules and maintains the UI overlap

**Expected behavior**
I expected the buttons to be clickable and not covered

**Screenshots**

![image](https://user-images.githubusercontent.com/30183293/148151126-3924533d-536e-4846-a730-5dc927490051.png)
![image](https://user-images.githubusercontent.com/30183293/148151187-824f8525-0889-4882-99b5-2741db94eba6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Additional context**
There wasn't any other issue. Things worked beautifully outside of the minor hiccup in the GUI. I appreciate you making this!
It would be nice if the GUI was changed to correct this - perhaps by using some of the empty space within the window's left side.

**Comment by padvincenzo** [comment]
Hi @Joey-Haney,
This is a good idea. I'll fix the GUI and upload a new version as soon as possible.
Thank you for your feedback, it is much appreciated.

**Comment by padvincenzo** [comment]
Hi @Joey-Haney 
I've uploaded a new version of Silence SpeedUp with the new GUI, you can check it out

**Comment by Joey-Haney** [comment]
I appreciate your efforts! This tool is saving me tons of time!
Thank you
