### ISSUE TITLE
[BUG] preference dialog box is not closed 

### ISSUE THREAD

**Issue by junoyoon** [padvincenzo/silence-speedup#7]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1000705/149988387-0752ac77-e815-47e2-9dc9-ffe09a77f964.png)
Save button above is not responsive.

**To Reproduce**
1. Open preference dialog box.
2. Click Save button

**Expected behavior**
The dialog box should be closed.

**Screenshots**
Already attached

**Desktop (please complete the following information):**
 - OS: OSX 
 - Version 12.1
 - 
**Additional context**
https://github.com/padvincenzo/silence-speedup/blob/7c9e7ae9e27599bbae25237cd632c3ad5fbbf72d/assets/pages/preferences/preferences.js#L60

dialog close should be called around above location.

**Comment by padvincenzo** [comment]
Hi @junoyoon 
This is, well, not a bug... I just dind't add any animation. In the next release the preference window will be closed (hidden) when the user click on "Save".

Thanks for your feedback

**Comment by padvincenzo** [comment]
Hi @junoyoon 
In the new version of Silence SpeedUp the `Save` button will close the preferences window, you can check it out

**Comment by junoyoon** [comment]
Thx!!! @padvincenzo

**Comment by junoyoon** [comment]
I confirmed the Save button is working now.

![image](https://user-images.githubusercontent.com/1000705/150079132-bccc998a-a319-4f87-88b1-b9e9b00cf99b.png)

Thx
